// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p15
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_SKYWORTHMSGSS_E0HFLT_H_
#define _TAO_IDL_SKYWORTHMSGSS_E0HFLT_H_


#include "SkyworthMsgsC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Fixed_Array_SArgument_T.h"
#include "tao/PortableServer/Var_Array_SArgument_T.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::EdgePolorPoint>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::EdgePolorPoint,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::EdgeXyzPoint>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::EdgeXyzPoint,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::DestXyzPoint>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::DestXyzPoint,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class SArg_Traits< ::SkyworthMsgs::EdgePolorPointList_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::SkyworthMsgs::EdgePolorPointList_var,
            ::SkyworthMsgs::EdgePolorPointList_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::DepthEdgeData>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::DepthEdgeData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::UltraTouchData>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::UltraTouchData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class SArg_Traits< ::SkyworthMsgs::RgbPicData_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::SkyworthMsgs::RgbPicData_var,
            ::SkyworthMsgs::RgbPicData_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::RgbPic>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::RgbPic,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class SArg_Traits< ::SkyworthMsgs::EdgeXyzPointList_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::SkyworthMsgs::EdgeXyzPointList_var,
            ::SkyworthMsgs::EdgeXyzPointList_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::ObsData>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::ObsData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanerStatus>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanerStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanerCommand>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanerCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::ElecQuantity>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::ElecQuantity,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::EmgStop>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::EmgStop,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::SlamStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::SlamStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::SlamCommand>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::SlamCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::SlamInteStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::SlamInteStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::SlamInteCommand>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::SlamInteCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::PatrolStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::PatrolStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::PatrolCommand>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::PatrolCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanCommand>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class SArg_Traits< ::SkyworthMsgs::MapPicData_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::SkyworthMsgs::MapPicData_var,
            ::SkyworthMsgs::MapPicData_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::MapLiveData>
    : public
        Fixed_Size_SArg_Traits_T<
            ::SkyworthMsgs::MapLiveData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::SlamManageStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::SlamManageStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::SlamManageCmd>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::SlamManageCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::PatrolManageStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::PatrolManageStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::PatrolManageCmd>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::PatrolManageCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanManageStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanManageStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanManageCmd>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanManageCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::MapLiveCmd>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::MapLiveCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanRouterStatus>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanRouterStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::SkyworthMsgs::CleanRouterCmd>
    : public
        Var_Size_SArg_Traits_T<
            ::SkyworthMsgs::CleanRouterCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:38

namespace POA_SkyworthMsgs
{
  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:69

} // module SkyworthMsgs

#endif /* ifndef */

