// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p15
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_SKYWORTHMSGSC_WRDPUC_H_
#define _TAO_IDL_SKYWORTHMSGSC_WRDPUC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Array_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Fixed_Array_Argument_T.h"
#include "tao/Var_Array_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace SkyworthMsgs
{

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct EdgePolorPoint;

  typedef
    ::TAO_Fixed_Var_T<
        EdgePolorPoint
      >
    EdgePolorPoint_var;

  typedef
    EdgePolorPoint &
    EdgePolorPoint_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  EdgePolorPoint
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef EdgePolorPoint_var _var_type;
    typedef EdgePolorPoint_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Float angle;
    ::CORBA::Float distance;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_EdgePolorPoint;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct EdgeXyzPoint;

  typedef
    ::TAO_Fixed_Var_T<
        EdgeXyzPoint
      >
    EdgeXyzPoint_var;

  typedef
    EdgeXyzPoint &
    EdgeXyzPoint_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  EdgeXyzPoint
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef EdgeXyzPoint_var _var_type;
    typedef EdgeXyzPoint_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Float x;
    ::CORBA::Float y;
    ::CORBA::Float z;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_EdgeXyzPoint;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DestXyzPoint;

  typedef
    ::TAO_Fixed_Var_T<
        DestXyzPoint
      >
    DestXyzPoint_var;

  typedef
    DestXyzPoint &
    DestXyzPoint_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DestXyzPoint
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DestXyzPoint_var _var_type;
    typedef DestXyzPoint_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Float x;
    ::CORBA::Float y;
    ::CORBA::Float z;
    ::CORBA::Float angle;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DestXyzPoint;

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef EdgePolorPoint EdgePolorPointList[360];
  typedef EdgePolorPoint EdgePolorPointList_slice;
  struct EdgePolorPointList_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        EdgePolorPointList,
        EdgePolorPointList_slice,
        EdgePolorPointList_tag
      >
    EdgePolorPointList_var;

  typedef
    EdgePolorPointList
    EdgePolorPointList_out;

  typedef
    TAO_Array_Forany_T<
        EdgePolorPointList,
        EdgePolorPointList_slice,
        EdgePolorPointList_tag
      >
    EdgePolorPointList_forany;

  TAO_NAMESPACE_STORAGE_CLASS EdgePolorPointList_slice *
  EdgePolorPointList_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  EdgePolorPointList_free (
      EdgePolorPointList_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS EdgePolorPointList_slice *
  EdgePolorPointList_dup (
      const EdgePolorPointList_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  EdgePolorPointList_copy (
      EdgePolorPointList_slice *_tao_to,
      const EdgePolorPointList_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_EdgePolorPointList;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DepthEdgeData;

  typedef
    ::TAO_Fixed_Var_T<
        DepthEdgeData
      >
    DepthEdgeData_var;

  typedef
    DepthEdgeData &
    DepthEdgeData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DepthEdgeData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DepthEdgeData_var _var_type;
    typedef DepthEdgeData_out _out_type;

    static void _tao_any_destructor (void *);
    
    SkyworthMsgs::EdgePolorPointList pointList;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DepthEdgeData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct UltraTouchData;

  typedef
    ::TAO_Fixed_Var_T<
        UltraTouchData
      >
    UltraTouchData_var;

  typedef
    UltraTouchData &
    UltraTouchData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  UltraTouchData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef UltraTouchData_var _var_type;
    typedef UltraTouchData_out _out_type;

    static void _tao_any_destructor (void *);
    
    SkyworthMsgs::EdgePolorPointList pointList;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_UltraTouchData;

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ::CORBA::Char RgbPicData[230400];
  typedef ::CORBA::Char RgbPicData_slice;
  struct RgbPicData_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        RgbPicData,
        RgbPicData_slice,
        RgbPicData_tag
      >
    RgbPicData_var;

  typedef
    RgbPicData
    RgbPicData_out;

  typedef
    TAO_Array_Forany_T<
        RgbPicData,
        RgbPicData_slice,
        RgbPicData_tag
      >
    RgbPicData_forany;

  TAO_NAMESPACE_STORAGE_CLASS RgbPicData_slice *
  RgbPicData_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  RgbPicData_free (
      RgbPicData_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS RgbPicData_slice *
  RgbPicData_dup (
      const RgbPicData_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  RgbPicData_copy (
      RgbPicData_slice *_tao_to,
      const RgbPicData_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_RgbPicData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct RgbPic;

  typedef
    ::TAO_Fixed_Var_T<
        RgbPic
      >
    RgbPic_var;

  typedef
    RgbPic &
    RgbPic_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  RgbPic
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef RgbPic_var _var_type;
    typedef RgbPic_out _out_type;

    static void _tao_any_destructor (void *);
    
    SkyworthMsgs::RgbPicData data;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_RgbPic;

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef EdgeXyzPoint EdgeXyzPointList[360];
  typedef EdgeXyzPoint EdgeXyzPointList_slice;
  struct EdgeXyzPointList_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        EdgeXyzPointList,
        EdgeXyzPointList_slice,
        EdgeXyzPointList_tag
      >
    EdgeXyzPointList_var;

  typedef
    EdgeXyzPointList
    EdgeXyzPointList_out;

  typedef
    TAO_Array_Forany_T<
        EdgeXyzPointList,
        EdgeXyzPointList_slice,
        EdgeXyzPointList_tag
      >
    EdgeXyzPointList_forany;

  TAO_NAMESPACE_STORAGE_CLASS EdgeXyzPointList_slice *
  EdgeXyzPointList_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  EdgeXyzPointList_free (
      EdgeXyzPointList_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS EdgeXyzPointList_slice *
  EdgeXyzPointList_dup (
      const EdgeXyzPointList_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  EdgeXyzPointList_copy (
      EdgeXyzPointList_slice *_tao_to,
      const EdgeXyzPointList_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_EdgeXyzPointList;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct ObsData;

  typedef
    ::TAO_Fixed_Var_T<
        ObsData
      >
    ObsData_var;

  typedef
    ObsData &
    ObsData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  ObsData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ObsData_var _var_type;
    typedef ObsData_out _out_type;

    static void _tao_any_destructor (void *);
    
    SkyworthMsgs::EdgeXyzPointList pointList;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ObsData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanerStatus;

  typedef
    ::TAO_Fixed_Var_T<
        CleanerStatus
      >
    CleanerStatus_var;

  typedef
    CleanerStatus &
    CleanerStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanerStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanerStatus_var _var_type;
    typedef CleanerStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Short status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanerStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanerCommand;

  typedef
    ::TAO_Var_Var_T<
        CleanerCommand
      >
    CleanerCommand_var;

  typedef
    ::TAO_Out_T<
        CleanerCommand
      >
    CleanerCommand_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanerCommand
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanerCommand_var _var_type;
    typedef CleanerCommand_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager cleanType;
    ::CORBA::Char cleanCommand;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanerCommand;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct ElecQuantity;

  typedef
    ::TAO_Var_Var_T<
        ElecQuantity
      >
    ElecQuantity_var;

  typedef
    ::TAO_Out_T<
        ElecQuantity
      >
    ElecQuantity_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  ElecQuantity
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ElecQuantity_var _var_type;
    typedef ElecQuantity_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager batteryType;
    ::CORBA::Float quantity;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ElecQuantity;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct EmgStop;

  typedef
    ::TAO_Fixed_Var_T<
        EmgStop
      >
    EmgStop_var;

  typedef
    EmgStop &
    EmgStop_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  EmgStop
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef EmgStop_var _var_type;
    typedef EmgStop_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Char emgStopCommand;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_EmgStop;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SlamStatus;

  typedef
    ::TAO_Var_Var_T<
        SlamStatus
      >
    SlamStatus_var;

  typedef
    ::TAO_Out_T<
        SlamStatus
      >
    SlamStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SlamStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SlamStatus_var _var_type;
    typedef SlamStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager statusType;
    ::CORBA::Short status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SlamStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SlamCommand;

  typedef
    ::TAO_Var_Var_T<
        SlamCommand
      >
    SlamCommand_var;

  typedef
    ::TAO_Out_T<
        SlamCommand
      >
    SlamCommand_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SlamCommand
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SlamCommand_var _var_type;
    typedef SlamCommand_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
    ::CORBA::Float distance;
    ::CORBA::Float angle;
    SkyworthMsgs::DestXyzPoint destPoint;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SlamCommand;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SlamInteStatus;

  typedef
    ::TAO_Var_Var_T<
        SlamInteStatus
      >
    SlamInteStatus_var;

  typedef
    ::TAO_Out_T<
        SlamInteStatus
      >
    SlamInteStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SlamInteStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SlamInteStatus_var _var_type;
    typedef SlamInteStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager statusType;
    ::CORBA::Char status;
    ::CORBA::Float machingDegree;
    SkyworthMsgs::EdgeXyzPointList obsData;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SlamInteStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SlamInteCommand;

  typedef
    ::TAO_Var_Var_T<
        SlamInteCommand
      >
    SlamInteCommand_var;

  typedef
    ::TAO_Out_T<
        SlamInteCommand
      >
    SlamInteCommand_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SlamInteCommand
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SlamInteCommand_var _var_type;
    typedef SlamInteCommand_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
    SkyworthMsgs::DestXyzPoint destPoint;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SlamInteCommand;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PatrolStatus;

  typedef
    ::TAO_Var_Var_T<
        PatrolStatus
      >
    PatrolStatus_var;

  typedef
    ::TAO_Out_T<
        PatrolStatus
      >
    PatrolStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PatrolStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PatrolStatus_var _var_type;
    typedef PatrolStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager statusType;
    ::CORBA::Char status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PatrolStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PatrolCommand;

  typedef
    ::TAO_Var_Var_T<
        PatrolCommand
      >
    PatrolCommand_var;

  typedef
    ::TAO_Out_T<
        PatrolCommand
      >
    PatrolCommand_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PatrolCommand
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PatrolCommand_var _var_type;
    typedef PatrolCommand_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
    SkyworthMsgs::DestXyzPoint destPoint;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PatrolCommand;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanStatus;

  typedef
    ::TAO_Var_Var_T<
        CleanStatus
      >
    CleanStatus_var;

  typedef
    ::TAO_Out_T<
        CleanStatus
      >
    CleanStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanStatus_var _var_type;
    typedef CleanStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager statusType;
    ::CORBA::Char status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanCommand;

  typedef
    ::TAO_Var_Var_T<
        CleanCommand
      >
    CleanCommand_var;

  typedef
    ::TAO_Out_T<
        CleanCommand
      >
    CleanCommand_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanCommand
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanCommand_var _var_type;
    typedef CleanCommand_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
    ::CORBA::Float distance;
    ::CORBA::Float angle;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanCommand;

  // TAO_IDL - Generated from
  // be/be_visitor_array/array_ch.cpp:54

  typedef ::CORBA::Char MapPicData[230400];
  typedef ::CORBA::Char MapPicData_slice;
  struct MapPicData_tag {};
  

  typedef
    TAO_FixedArray_Var_T<
        MapPicData,
        MapPicData_slice,
        MapPicData_tag
      >
    MapPicData_var;

  typedef
    MapPicData
    MapPicData_out;

  typedef
    TAO_Array_Forany_T<
        MapPicData,
        MapPicData_slice,
        MapPicData_tag
      >
    MapPicData_forany;

  TAO_NAMESPACE_STORAGE_CLASS MapPicData_slice *
  MapPicData_alloc (void);

  TAO_NAMESPACE_STORAGE_CLASS void
  MapPicData_free (
      MapPicData_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS MapPicData_slice *
  MapPicData_dup (
      const MapPicData_slice *_tao_slice);
  
  TAO_NAMESPACE_STORAGE_CLASS void
  MapPicData_copy (
      MapPicData_slice *_tao_to,
      const MapPicData_slice *_tao_from);

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_MapPicData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct MapLiveData;

  typedef
    ::TAO_Fixed_Var_T<
        MapLiveData
      >
    MapLiveData_var;

  typedef
    MapLiveData &
    MapLiveData_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  MapLiveData
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef MapLiveData_var _var_type;
    typedef MapLiveData_out _out_type;

    static void _tao_any_destructor (void *);
    
    SkyworthMsgs::MapPicData data;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_MapLiveData;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SlamManageStatus;

  typedef
    ::TAO_Var_Var_T<
        SlamManageStatus
      >
    SlamManageStatus_var;

  typedef
    ::TAO_Out_T<
        SlamManageStatus
      >
    SlamManageStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SlamManageStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SlamManageStatus_var _var_type;
    typedef SlamManageStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager statusType;
    ::CORBA::Char status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SlamManageStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SlamManageCmd;

  typedef
    ::TAO_Var_Var_T<
        SlamManageCmd
      >
    SlamManageCmd_var;

  typedef
    ::TAO_Out_T<
        SlamManageCmd
      >
    SlamManageCmd_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SlamManageCmd
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SlamManageCmd_var _var_type;
    typedef SlamManageCmd_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
    ::CORBA::Float distance;
    ::CORBA::Float angle;
    SkyworthMsgs::DestXyzPoint destPoint;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SlamManageCmd;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PatrolManageStatus;

  typedef
    ::TAO_Var_Var_T<
        PatrolManageStatus
      >
    PatrolManageStatus_var;

  typedef
    ::TAO_Out_T<
        PatrolManageStatus
      >
    PatrolManageStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PatrolManageStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PatrolManageStatus_var _var_type;
    typedef PatrolManageStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager area;
    ::TAO::String_Manager statusType;
    ::CORBA::Char status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PatrolManageStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PatrolManageCmd;

  typedef
    ::TAO_Var_Var_T<
        PatrolManageCmd
      >
    PatrolManageCmd_var;

  typedef
    ::TAO_Out_T<
        PatrolManageCmd
      >
    PatrolManageCmd_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PatrolManageCmd
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PatrolManageCmd_var _var_type;
    typedef PatrolManageCmd_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager area;
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PatrolManageCmd;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanManageStatus;

  typedef
    ::TAO_Var_Var_T<
        CleanManageStatus
      >
    CleanManageStatus_var;

  typedef
    ::TAO_Out_T<
        CleanManageStatus
      >
    CleanManageStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanManageStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanManageStatus_var _var_type;
    typedef CleanManageStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager statusType;
    ::CORBA::Char status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanManageStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanManageCmd;

  typedef
    ::TAO_Var_Var_T<
        CleanManageCmd
      >
    CleanManageCmd_var;

  typedef
    ::TAO_Out_T<
        CleanManageCmd
      >
    CleanManageCmd_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanManageCmd
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanManageCmd_var _var_type;
    typedef CleanManageCmd_out _out_type;

    static void _tao_any_destructor (void *);
    
    SkyworthMsgs::EdgeXyzPoint point1;
    SkyworthMsgs::EdgeXyzPoint point2;
    SkyworthMsgs::EdgeXyzPoint point3;
    SkyworthMsgs::EdgeXyzPoint point4;
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanManageCmd;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct MapLiveCmd;

  typedef
    ::TAO_Var_Var_T<
        MapLiveCmd
      >
    MapLiveCmd_var;

  typedef
    ::TAO_Out_T<
        MapLiveCmd
      >
    MapLiveCmd_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  MapLiveCmd
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef MapLiveCmd_var _var_type;
    typedef MapLiveCmd_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_MapLiveCmd;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanRouterStatus;

  typedef
    ::TAO_Var_Var_T<
        CleanRouterStatus
      >
    CleanRouterStatus_var;

  typedef
    ::TAO_Out_T<
        CleanRouterStatus
      >
    CleanRouterStatus_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanRouterStatus
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanRouterStatus_var _var_type;
    typedef CleanRouterStatus_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::TAO::String_Manager statusType;
    ::CORBA::Char status;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanRouterStatus;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct CleanRouterCmd;

  typedef
    ::TAO_Var_Var_T<
        CleanRouterCmd
      >
    CleanRouterCmd_var;

  typedef
    ::TAO_Out_T<
        CleanRouterCmd
      >
    CleanRouterCmd_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  CleanRouterCmd
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef CleanRouterCmd_var _var_type;
    typedef CleanRouterCmd_out _out_type;

    static void _tao_any_destructor (void *);
    
    SkyworthMsgs::EdgeXyzPoint point1;
    SkyworthMsgs::EdgeXyzPoint point2;
    SkyworthMsgs::EdgeXyzPoint point3;
    SkyworthMsgs::EdgeXyzPoint point4;
    ::TAO::String_Manager area;
    ::TAO::String_Manager commandType;
    ::CORBA::Char command;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_CleanRouterCmd;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module SkyworthMsgs

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::EdgePolorPoint>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::EdgePolorPoint,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::EdgeXyzPoint>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::EdgeXyzPoint,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::DestXyzPoint>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::DestXyzPoint,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class Arg_Traits< ::SkyworthMsgs::EdgePolorPointList_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::SkyworthMsgs::EdgePolorPointList_var,
            ::SkyworthMsgs::EdgePolorPointList_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::DepthEdgeData>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::DepthEdgeData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::UltraTouchData>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::UltraTouchData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class Arg_Traits< ::SkyworthMsgs::RgbPicData_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::SkyworthMsgs::RgbPicData_var,
            ::SkyworthMsgs::RgbPicData_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::RgbPic>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::RgbPic,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class Arg_Traits< ::SkyworthMsgs::EdgeXyzPointList_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::SkyworthMsgs::EdgeXyzPointList_var,
            ::SkyworthMsgs::EdgeXyzPointList_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::ObsData>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::ObsData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanerStatus>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanerStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanerCommand>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanerCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::ElecQuantity>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::ElecQuantity,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::EmgStop>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::EmgStop,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::SlamStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::SlamStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::SlamCommand>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::SlamCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::SlamInteStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::SlamInteStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::SlamInteCommand>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::SlamInteCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::PatrolStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::PatrolStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::PatrolCommand>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::PatrolCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanCommand>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanCommand,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  template<>
  class Arg_Traits< ::SkyworthMsgs::MapPicData_tag>
    : public
        Fixed_Array_Arg_Traits_T<
            ::SkyworthMsgs::MapPicData_var,
            ::SkyworthMsgs::MapPicData_forany,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::MapLiveData>
    : public
        Fixed_Size_Arg_Traits_T<
            ::SkyworthMsgs::MapLiveData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::SlamManageStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::SlamManageStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::SlamManageCmd>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::SlamManageCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::PatrolManageStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::PatrolManageStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::PatrolManageCmd>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::PatrolManageCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanManageStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanManageStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanManageCmd>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanManageCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::MapLiveCmd>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::MapLiveCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanRouterStatus>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanRouterStatus,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::SkyworthMsgs::CleanRouterCmd>
    : public
        Var_Size_Arg_Traits_T<
            ::SkyworthMsgs::CleanRouterCmd,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
  template<>
  struct  Array_Traits<
      SkyworthMsgs::EdgePolorPointList_forany
    >
  {
    static void free (
        SkyworthMsgs::EdgePolorPointList_slice * _tao_slice);
    static SkyworthMsgs::EdgePolorPointList_slice * dup (
        const SkyworthMsgs::EdgePolorPointList_slice * _tao_slice);
    static void copy (
        SkyworthMsgs::EdgePolorPointList_slice * _tao_to,
        const SkyworthMsgs::EdgePolorPointList_slice * _tao_from);
    static SkyworthMsgs::EdgePolorPointList_slice * alloc (void);
    static void zero (
        SkyworthMsgs::EdgePolorPointList_slice * _tao_slice);
  };
  template<>
  struct  Array_Traits<
      SkyworthMsgs::RgbPicData_forany
    >
  {
    static void free (
        SkyworthMsgs::RgbPicData_slice * _tao_slice);
    static SkyworthMsgs::RgbPicData_slice * dup (
        const SkyworthMsgs::RgbPicData_slice * _tao_slice);
    static void copy (
        SkyworthMsgs::RgbPicData_slice * _tao_to,
        const SkyworthMsgs::RgbPicData_slice * _tao_from);
    static SkyworthMsgs::RgbPicData_slice * alloc (void);
    static void zero (
        SkyworthMsgs::RgbPicData_slice * _tao_slice);
  };
  template<>
  struct  Array_Traits<
      SkyworthMsgs::EdgeXyzPointList_forany
    >
  {
    static void free (
        SkyworthMsgs::EdgeXyzPointList_slice * _tao_slice);
    static SkyworthMsgs::EdgeXyzPointList_slice * dup (
        const SkyworthMsgs::EdgeXyzPointList_slice * _tao_slice);
    static void copy (
        SkyworthMsgs::EdgeXyzPointList_slice * _tao_to,
        const SkyworthMsgs::EdgeXyzPointList_slice * _tao_from);
    static SkyworthMsgs::EdgeXyzPointList_slice * alloc (void);
    static void zero (
        SkyworthMsgs::EdgeXyzPointList_slice * _tao_slice);
  };
  template<>
  struct  Array_Traits<
      SkyworthMsgs::MapPicData_forany
    >
  {
    static void free (
        SkyworthMsgs::MapPicData_slice * _tao_slice);
    static SkyworthMsgs::MapPicData_slice * dup (
        const SkyworthMsgs::MapPicData_slice * _tao_slice);
    static void copy (
        SkyworthMsgs::MapPicData_slice * _tao_to,
        const SkyworthMsgs::MapPicData_slice * _tao_from);
    static SkyworthMsgs::MapPicData_slice * alloc (void);
    static void zero (
        SkyworthMsgs::MapPicData_slice * _tao_slice);
  };
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::EdgePolorPoint &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::EdgePolorPoint*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::EdgePolorPoint *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::EdgePolorPoint *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::EdgePolorPoint &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::EdgePolorPoint*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::EdgePolorPoint *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::EdgePolorPoint *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::EdgeXyzPoint &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::EdgeXyzPoint*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::EdgeXyzPoint *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::EdgeXyzPoint *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::EdgeXyzPoint &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::EdgeXyzPoint*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::EdgeXyzPoint *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::EdgeXyzPoint *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::DestXyzPoint &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::DestXyzPoint*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::DestXyzPoint *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::DestXyzPoint *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::DestXyzPoint &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::DestXyzPoint*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::DestXyzPoint *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::DestXyzPoint *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_array/any_op_ch.cpp:40


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::EdgePolorPointList_forany &);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::EdgePolorPointList_forany &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::DepthEdgeData &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::DepthEdgeData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::DepthEdgeData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::DepthEdgeData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::DepthEdgeData &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::DepthEdgeData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::DepthEdgeData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::DepthEdgeData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::UltraTouchData &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::UltraTouchData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::UltraTouchData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::UltraTouchData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::UltraTouchData &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::UltraTouchData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::UltraTouchData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::UltraTouchData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_array/any_op_ch.cpp:40


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::RgbPicData_forany &);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::RgbPicData_forany &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::RgbPic &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::RgbPic*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::RgbPic *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::RgbPic *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::RgbPic &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::RgbPic*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::RgbPic *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::RgbPic *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_array/any_op_ch.cpp:40


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::EdgeXyzPointList_forany &);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::EdgeXyzPointList_forany &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::ObsData &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::ObsData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::ObsData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::ObsData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::ObsData &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::ObsData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::ObsData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::ObsData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanerStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanerStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanerStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanerStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanerStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanerStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanerStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanerStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanerCommand &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanerCommand*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanerCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanerCommand *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanerCommand &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanerCommand*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanerCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanerCommand *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::ElecQuantity &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::ElecQuantity*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::ElecQuantity *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::ElecQuantity *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::ElecQuantity &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::ElecQuantity*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::ElecQuantity *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::ElecQuantity *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::EmgStop &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::EmgStop*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::EmgStop *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::EmgStop *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::EmgStop &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::EmgStop*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::EmgStop *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::EmgStop *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::SlamStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::SlamStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::SlamStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::SlamStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::SlamStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::SlamStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::SlamStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::SlamStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::SlamCommand &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::SlamCommand*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::SlamCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::SlamCommand *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::SlamCommand &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::SlamCommand*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::SlamCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::SlamCommand *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::SlamInteStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::SlamInteStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::SlamInteStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::SlamInteStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::SlamInteStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::SlamInteStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::SlamInteStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::SlamInteStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::SlamInteCommand &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::SlamInteCommand*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::SlamInteCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::SlamInteCommand *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::SlamInteCommand &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::SlamInteCommand*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::SlamInteCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::SlamInteCommand *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::PatrolStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::PatrolStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::PatrolStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::PatrolStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::PatrolStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::PatrolStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::PatrolStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::PatrolStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::PatrolCommand &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::PatrolCommand*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::PatrolCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::PatrolCommand *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::PatrolCommand &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::PatrolCommand*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::PatrolCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::PatrolCommand *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanCommand &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanCommand*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanCommand *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanCommand &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanCommand*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanCommand *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanCommand *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_array/any_op_ch.cpp:40


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::MapPicData_forany &);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::MapPicData_forany &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::MapLiveData &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::MapLiveData*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::MapLiveData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::MapLiveData *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::MapLiveData &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::MapLiveData*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::MapLiveData *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::MapLiveData *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::SlamManageStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::SlamManageStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::SlamManageStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::SlamManageStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::SlamManageStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::SlamManageStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::SlamManageStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::SlamManageStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::SlamManageCmd &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::SlamManageCmd*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::SlamManageCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::SlamManageCmd *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::SlamManageCmd &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::SlamManageCmd*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::SlamManageCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::SlamManageCmd *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::PatrolManageStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::PatrolManageStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::PatrolManageStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::PatrolManageStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::PatrolManageStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::PatrolManageStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::PatrolManageStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::PatrolManageStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::PatrolManageCmd &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::PatrolManageCmd*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::PatrolManageCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::PatrolManageCmd *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::PatrolManageCmd &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::PatrolManageCmd*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::PatrolManageCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::PatrolManageCmd *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanManageStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanManageStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanManageStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanManageStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanManageStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanManageStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanManageStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanManageStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanManageCmd &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanManageCmd*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanManageCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanManageCmd *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanManageCmd &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanManageCmd*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanManageCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanManageCmd *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::MapLiveCmd &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::MapLiveCmd*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::MapLiveCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::MapLiveCmd *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::MapLiveCmd &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::MapLiveCmd*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::MapLiveCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::MapLiveCmd *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanRouterStatus &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanRouterStatus*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanRouterStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanRouterStatus *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanRouterStatus &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanRouterStatus*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanRouterStatus *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanRouterStatus *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace SkyworthMsgs
{
   void operator<<= (::CORBA::Any &, const ::SkyworthMsgs::CleanRouterCmd &); // copying version
   void operator<<= (::CORBA::Any &, ::SkyworthMsgs::CleanRouterCmd*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::SkyworthMsgs::CleanRouterCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::SkyworthMsgs::CleanRouterCmd *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const SkyworthMsgs::CleanRouterCmd &); // copying version
 void operator<<= (::CORBA::Any &, SkyworthMsgs::CleanRouterCmd*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, SkyworthMsgs::CleanRouterCmd *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const SkyworthMsgs::CleanRouterCmd *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::EdgePolorPoint &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::EdgePolorPoint &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::EdgeXyzPoint &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::EdgeXyzPoint &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::DestXyzPoint &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::DestXyzPoint &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 CORBA::Boolean operator<< (TAO_OutputCDR &strm, const SkyworthMsgs::EdgePolorPointList_forany &_tao_array);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::EdgePolorPointList_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::DepthEdgeData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::DepthEdgeData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::UltraTouchData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::UltraTouchData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 CORBA::Boolean operator<< (TAO_OutputCDR &strm, const SkyworthMsgs::RgbPicData_forany &_tao_array);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::RgbPicData_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::RgbPic &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::RgbPic &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 CORBA::Boolean operator<< (TAO_OutputCDR &strm, const SkyworthMsgs::EdgeXyzPointList_forany &_tao_array);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::EdgeXyzPointList_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::ObsData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::ObsData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanerStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanerStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanerCommand &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanerCommand &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::ElecQuantity &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::ElecQuantity &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::EmgStop &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::EmgStop &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::SlamStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::SlamStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::SlamCommand &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::SlamCommand &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::SlamInteStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::SlamInteStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::SlamInteCommand &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::SlamInteCommand &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::PatrolStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::PatrolStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::PatrolCommand &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::PatrolCommand &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanCommand &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanCommand &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_array/cdr_op_ch.cpp:102


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 CORBA::Boolean operator<< (TAO_OutputCDR &strm, const SkyworthMsgs::MapPicData_forany &_tao_array);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::MapPicData_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::MapLiveData &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::MapLiveData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::SlamManageStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::SlamManageStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::SlamManageCmd &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::SlamManageCmd &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::PatrolManageStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::PatrolManageStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::PatrolManageCmd &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::PatrolManageCmd &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanManageStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanManageStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanManageCmd &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanManageCmd &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::MapLiveCmd &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::MapLiveCmd &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanRouterStatus &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanRouterStatus &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const SkyworthMsgs::CleanRouterCmd &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, SkyworthMsgs::CleanRouterCmd &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "SkyworthMsgsC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

